### ISSUE TITLE
Toggling mod, instead of removal

### ISSUE THREAD

**Issue by piotrszymaniec** [maxbourdarie/Path-Of-Exile-Finer-Search-Options#3]
**Describe the bug**
After clicking - button on add to filters panel, its adding those modes

**To Reproduce**
1. Go to trade site/have clear search filters
2. Click on any of "add to filters" - button
3. check contents of search filter panel

**Expected behavior**
Clicking on mod "should" only remove that mod if its value is 0
Also there is niche problem if someone wants values less then 0. 
But lets asume that is edge case.

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Win7
 - Browser Opera
 - Version 67.0 (Chrome/80.0.3987.132)

**Smartphone (please complete the following information):**
none

**Additional context**

**Comment by maxbourdarie** [comment]
Hi, thank you for letting me know ! 
Version 1.1.2 should fix the "toggling" part
when the mods don't exist in the filters, clicking "-" does not add them in the filters anymore

I dont know yet how to handle the <0 edge case so for now I don't think i'll be able to fix it
However in the case of the "common mods" buttons it should not be a problem, as one generally wants >0 life/resists/move speed, if any.

Have a good day, thanks for contributing !
